--addauthor(author_name)
BEGIN
addauthor('Laura Hillenbrand');
addauthor('Kenn Mogg');
addauthor('Hans Johannes Hoefer');
addauthor('Felicity Trotman');
addauthor('House Random');
addauthor('Houghton Mifflin');
addauthor('Drowning Douglas');
addauthor('Robert Hendrickson');
addauthor('The Onion');
addauthor('J. R. Parrish');
addauthor('Suzanne Weyn');
addauthor('Chuck Hill');
addauthor('Joseph Leeming');
addauthor('Chuck Hill');
addauthor('Anne Tyler');
addauthor('H. Jackson Brown');
addauthor('Eric Garcia');
addauthor('Miriam Austin');
addauthor('Kathleen Duey');
addauthor('Richard Bassett');
addauthor('John Wiley');
addauthor('David Iglehart');
addauthor('Richard Bassett');
addauthor('Greg Critser');
addauthor('John Kane');
addauthor('David Cordingly');
addauthor('Sheila Heti');
addauthor('Julia Oliver');
addauthor('Toni Morrison');
addauthor('Barbara Kingsolver');
addauthor('Anne Rivers Siddons');
addauthor('Charles Noland');
addauthor('Robert A. Heinlein');
addauthor('Adair Lara');
addauthor('Sarah Tucker');
addauthor('Patricia Pearson');
addauthor('Amy Tan');
addauthor('Jack Canfield');
addauthor('Celia Brooks Brown');
addauthor('M.D. Bernie S. Siegel');
addauthor('Darcy Cosper');
addauthor('Martha Nibley Beck');
addauthor('John M. Gottman');
addauthor('E. J. W. Barber');
addauthor('John Grisham');
addauthor('Anita Ganeri');
addauthor('J.D. Robb');
addauthor('Deepak Chopra');
addauthor('Benjamin Hoff');
addauthor('Richard Bruce Wright');
addauthor('Scott Turow');
addauthor('R. J. Kaiser');
addauthor('Rich Shapero');
addauthor('Michael Crichton');
addauthor('Arthur Philips');
addauthor('Harper Lee');
addauthor('Joseph Conrad');
addauthor('Niccolo Machiavelli');
addauthor('Philip Pullman');
addauthor('Mike Gayle');
addauthor('Alma Alexander');
addauthor('DesTe_Carlo');
addauthor('Gina Bari Kolata');
addauthor('Hist Lor');
addauthor('Dean Koontz');
addauthor('Patricia Cornwell');
addauthor('Amy Tan');
addauthor('Valerie Frankel');
addauthor('Sandra Levy Ceren');
addauthor('April Smith');
addauthor('Dan Savage');
DBMS_OUTPUT.PUT_LINE('Rows Created: || SQL%ROWCOUNT');
END;




