package librarysystem;


import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ryou Hikaru
 */
public class AddBookDialog extends javax.swing.JDialog {
    private static CallableStatement cst;
    private static Connection con;
    /**
     * Creates new form EditUserDialog
     * @param parent the component calling this class
     * @param con the connection to database
     */
    public AddBookDialog(java.awt.Dialog parent, Connection con) {
        super(parent);
        initComponents();
        
        this.con = con;
        
        this.getContentPane().setBackground(new java.awt.Color(242,223,167));
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        isbnLabel = new javax.swing.JLabel();
        copyLabel = new javax.swing.JLabel();
        isbnField = new javax.swing.JTextField();
        titleField = new javax.swing.JTextField();
        copynoLabel = new javax.swing.JLabel();
        copyField = new javax.swing.JTextField();
        authorLabel = new javax.swing.JLabel();
        authorField = new javax.swing.JTextField();
        shelfLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        yearField = new javax.swing.JTextField();
        placeField = new javax.swing.JTextField();
        placeLabel = new javax.swing.JLabel();
        shelfField = new javax.swing.JComboBox();
        statusField = new javax.swing.JComboBox();
        addLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit book");
        setBackground(new java.awt.Color(242, 223, 167));

        jPanel1.setBackground(new java.awt.Color(248, 238, 210));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        isbnLabel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        isbnLabel.setText("ISBN no.");

        copyLabel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        copyLabel.setText("Copy no.");

        copynoLabel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        copynoLabel.setText("Title");

        authorLabel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        authorLabel.setText("Author");

        shelfLabel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        shelfLabel.setText("Shelf");

        statusLabel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        statusLabel.setText("Status");

        yearLabel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        yearLabel.setText("Year Published");

        placeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeFieldActionPerformed(evt);
            }
        });

        placeLabel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        placeLabel.setText("Place of Publication");

        shelfField.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Fiction", "Non-Fiction", "Computer Science, Information and General Works", "Social Sciences", "Arts and Recreation", "History and Geography", "Literature", "Language", "Philosophy and Psychology", "Pure Science"}));

        statusField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "STORED", "RESERVED", "WITHDRAWN"}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(placeLabel)
                    .addComponent(copynoLabel)
                    .addComponent(isbnLabel)
                    .addComponent(copyLabel)
                    .addComponent(authorLabel)
                    .addComponent(shelfLabel)
                    .addComponent(statusLabel)
                    .addComponent(yearLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorField)
                    .addComponent(copyField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(titleField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(isbnField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(yearField)
                    .addComponent(placeField)
                    .addComponent(shelfField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusField, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isbnLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copynoLabel)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copyLabel)
                    .addComponent(copyField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorLabel)
                    .addComponent(authorField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shelfField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shelfLabel))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLabel))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placeLabel)
                    .addComponent(placeField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        addLabel.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        addLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addLabel.setText("New Book");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(addLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String isbn = isbnField.getText();
        String title = titleField.getText();
        String copynum = copyField.getText();
        String author = authorField.getText();
        String shelf = shelfField.getSelectedItem().toString();
        String status = statusField.getSelectedItem().toString();
        String year = yearField.getText();
        String place = placeField.getText();
        
        if (validNumber(isbn) == false || validNumber(copynum) == false || validNumber(year) == false) {
            JOptionPane.showMessageDialog(rootPane, "ISBN no, Copy no, and  Year should be numeric", "Invalid numeric input", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        try {
            cst = con.prepareCall("{CALL addbookandwrittenwork(?,?,?,?,?,?,?,?)}");
            cst.setString(1, isbn);
            cst.setString(2, title);
            cst.setString(3, copynum);
            cst.setString(4, author);
            cst.setString(5, shelf);
            cst.setString(6, status);
            cst.setString(7, year);
            cst.setString(8, place);
            
            int confirmation = JOptionPane.showConfirmDialog(rootPane, "Are you sure to add this book?", "Add book", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (confirmation == 0) {
                cst.execute();
                JOptionPane.showMessageDialog(rootPane, "Book added!", "Add book", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
        catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void placeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeFieldActionPerformed
  
    private boolean validNumber(String str) {
        boolean valid = true;
        int length = str.length();
        
        for (int i = 0; i < length; i++) {
            if (str.charAt(i) >= 48 && str.charAt(i) <= 57) {
                valid = true;
            }
            else {
                valid = false; 
                break;
            }
        }
        return valid;   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField authorField;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField copyField;
    private javax.swing.JLabel copyLabel;
    private javax.swing.JLabel copynoLabel;
    private javax.swing.JTextField isbnField;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField placeField;
    private javax.swing.JLabel placeLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox shelfField;
    private javax.swing.JLabel shelfLabel;
    private javax.swing.JComboBox statusField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField titleField;
    private javax.swing.JTextField yearField;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
