package librarysystem;


import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleCallableStatement;
import oracle.jdbc.OracleTypes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ryou Hikaru
 */
public class LibrarianManageUser extends javax.swing.JDialog {
    private static CallableStatement cst;
    private static Connection con;
    private static String loginId;
    private DefaultTableModel dModel;
    private Object[][] data;
    /**
     * Creates new form LibrarianManageUser
     */
    public LibrarianManageUser(java.awt.Frame parent, Connection con) {
        super(parent);
        
        this.con = con;
        
        initComponents();
        
        this.getContentPane().setBackground(new java.awt.Color(242,223,167));
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchHint = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        userDetailsTable = new javax.swing.JTable();
        returnButton = new javax.swing.JButton();
        editUserButton = new javax.swing.JButton();
        addUserButton = new javax.swing.JButton();
        deleteUserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        searchHint.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        searchHint.setText("Search for user by Login ID");

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search1.png"))); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        userDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Login ID", "Last Name", "First Name", "Middle Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPane.setViewportView(userDetailsTable);

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        editUserButton.setText("Edit user");
        editUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserButtonActionPerformed(evt);
            }
        });

        addUserButton.setText("Add user");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        deleteUserButton.setText("Delete user");
        deleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchHint))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton))
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(searchHint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnButton)
                    .addComponent(editUserButton)
                    .addComponent(addUserButton)
                    .addComponent(deleteUserButton))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        setTableData();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void editUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserButtonActionPerformed
        int row = userDetailsTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(rootPane, "Please select a user", "Edit User", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            String id = userDetailsTable.getValueAt(row, 0).toString();
            System.out.println(id);
            new EditUserDialog(this, con, id).setVisible(true);
        }
    }//GEN-LAST:event_editUserButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        String sql = "SELECT id_seq2.NEXTVAL FROM dual";
        int nextVal = 0;
        synchronized(this) {
            try {
                PreparedStatement stmt = con.prepareStatement(sql);
                ResultSet rs = stmt.executeQuery();
                if (rs.next()) {
                    nextVal = rs.getInt(1);
                }
            } catch (SQLException ex) {System.out.println(ex.getMessage());}
        }  
        new AddUserDialog(this, con, nextVal).setVisible(true);
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserButtonActionPerformed
        int row = userDetailsTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(rootPane, "Please select a user", "Delete User", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            String id = userDetailsTable.getValueAt(row, 0).toString();
            int confirmation = JOptionPane.showConfirmDialog(rootPane, "Delete this user?", "Delete User", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirmation == 0) {
                try {
                    cst = con.prepareCall("{CALL deleteuser(?)}");
                    cst.setInt(1, Integer.parseInt(id));
                    cst.execute();
                    JOptionPane.showMessageDialog(rootPane, "User " + id + " deleted");
                } catch (SQLException ex) {}
                setTableData();
            }
            else {
                return;
            }
        }
    }//GEN-LAST:event_deleteUserButtonActionPerformed
    private Object[] searchUserColumns() {
        Object[] ret = {"Login ID", "Last Name", "First Name", "Middle Name"};
        return ret;
    }
    private void setTableData() {
        loginId = searchTextField.getText();
        if (validNumber(loginId) == false) {
            JOptionPane.showMessageDialog(rootPane, "Login ID can only be numbers", "Invalid input", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try {
            cst = con.prepareCall("{CALL retrieveUsers(?, ?)}");
            cst.setString(1, loginId);
            cst.registerOutParameter(2, OracleTypes.CURSOR);
            
            cst.execute();
            ResultSet rs = ((OracleCallableStatement)cst).getCursor(2);
            int i = 0;
            while (rs.next()) {             
                i++;
            }   
            
            data = new Object[i][searchUserColumns().length];
            dModel = new DefaultTableModel(data, searchUserColumns());
            userDetailsTable.setModel(dModel);
            
            cst.execute();
            ResultSet finalRs = ((OracleCallableStatement)cst).getCursor(2);
            i = 0;
            while (finalRs.next()) {
                dModel.setValueAt(finalRs.getInt("loginid"), i, 0);
                dModel.setValueAt(finalRs.getString("last_name"), i, 1);
                dModel.setValueAt(finalRs.getString("first_name"), i, 2);
                dModel.setValueAt(finalRs.getString("middle_name"), i, 3);
                i++;
            } 
            
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    private boolean validNumber(String str) {
        boolean valid = true;
        int length = str.length();
        
        for (int i = 0; i < length; i++) {
            if (str.charAt(i) >= 48 && str.charAt(i) <= 57) {
                valid = true;
            }
            else {
                valid = false; 
                break;
            }
        }
        return valid;   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserButton;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JButton editUserButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchHint;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTable userDetailsTable;
    // End of variables declaration//GEN-END:variables
}
