package librarysystem;


import java.sql.Connection;
import java.sql.SQLException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shanice Vergonia
 */
public class PatronMainScreen extends javax.swing.JFrame {
    private String patronId;
    private static Connection con;
    /**
     * Creates new form PatronManScreen
     */
    public PatronMainScreen(String patronId, Connection con) {
        initComponents();
        
        this.patronId = patronId;
        this.con = con;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome1_label = new javax.swing.JLabel();
        viewTransactionsButton = new javax.swing.JButton();
        searchBook_b = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        options1_jmenu = new javax.swing.JMenu();
        menu_logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(null);
        setMinimumSize(null);
        setPreferredSize(new java.awt.Dimension(350, 540));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        welcome1_label.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        welcome1_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/welcome_patron.png"))); // NOI18N
        welcome1_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(welcome1_label);
        welcome1_label.setBounds(60, 100, 210, 70);

        viewTransactionsButton.setBackground(new java.awt.Color(242, 223, 167));
        viewTransactionsButton.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        viewTransactionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search1.png"))); // NOI18N
        viewTransactionsButton.setText("View Transactions");
        viewTransactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTransactionsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewTransactionsButton);
        viewTransactionsButton.setBounds(70, 210, 180, 40);

        searchBook_b.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        searchBook_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book.png"))); // NOI18N
        searchBook_b.setText("Search Book");
        searchBook_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBook_bActionPerformed(evt);
            }
        });
        getContentPane().add(searchBook_b);
        searchBook_b.setBounds(80, 260, 160, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library-services4.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 350, 540);

        options1_jmenu.setText("Options");
        options1_jmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                options1_jmenuActionPerformed(evt);
            }
        });

        menu_logout.setText("Logout");
        menu_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_logoutActionPerformed(evt);
            }
        });
        options1_jmenu.add(menu_logout);

        jMenuBar1.add(options1_jmenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBook_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBook_bActionPerformed
        // TODO add your handling code here:
        new PatronSearchBook(this, patronId, con).setVisible(true);
    }//GEN-LAST:event_searchBook_bActionPerformed

    private void menu_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_logoutActionPerformed
        try {
            new PatronLogin().setVisible(true); 
        }
        catch(SQLException e) {}
        this.dispose();
    }//GEN-LAST:event_menu_logoutActionPerformed

    private void options1_jmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_options1_jmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_options1_jmenuActionPerformed

    private void viewTransactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTransactionsButtonActionPerformed
        new PatronViewTransaction(this, patronId, con).setVisible(true);
    }//GEN-LAST:event_viewTransactionsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menu_logout;
    private javax.swing.JMenu options1_jmenu;
    private javax.swing.JButton searchBook_b;
    private javax.swing.JButton viewTransactionsButton;
    private javax.swing.JLabel welcome1_label;
    // End of variables declaration//GEN-END:variables
}
